### ISSUE TITLE
HoloAPI 2.0.0 - touch holograms not working any more

### ISSUE THREAD

**Issue by desht** [DSH105/HoloAPI#100]
I'm using HoloAPI from ScrollingMenuSign to implement hologram menu views.  This class is where I create holograms: https://github.com/desht/ScrollingMenuSign/blob/master/src/main/java/me/desht/scrollingmenusign/views/SMSPublicHoloView.java - buildHologram() at line 64 is where I actually create the hologram.  I'm using `.withSimplicity(true)` since SMS does all the hologram management and I don't need HoloAPI to save the holograms that the SMS view creates.

It all worked fine with HoloAPI 1.2.4, but the holograms that appear now are unresponsive to any touch action.  Has something else changed in the 1.2.4 -> 2.0.0 transition that I've missed?

In a separate but related problem, these holograms that I'm creating with the simplicity flag do still seem to be getting persisted by HoloAPI in 2.0.0, which wasn't the case in 1.2.4.  I can see entries for the holograms I'm creating in HoloAPI's data.yml file which I thought should not be the case for holograms with the simplicity flag.

**Comment by CaptainBern** [comment]
Note that 2.0 only supports 1.7.6 and above. (Preferably 1.7.9 or 1.7.10)

**Comment by desht** [comment]
Yep, I'm testing this on 1.7.10 (primarily because 1.2.4 doesn't appear to work on 1.7.10 and I want to have a version of SMS ready soon with 1.7.10 support).

**Comment by CaptainBern** [comment]
I am having some issues with my internet at the moment so I can't really fix it now. My internet should be fixed on monday, I will take a look at it then and see what I can do. I will also take a look at the simplicity stuff, we've had some trouble with it before...

**Comment by desht** [comment]
No worries, just wanted to get the issue reported.  It's in a dev build of HoloAPI used by a dev build of SMS on a dev build of CraftBukkit, so I'm not overly concerned at this point :)

**Comment by CaptainBern** [comment]
I've been investigating this for a few days now and can't really seem to find why/what causes it. Or something has changed client-side, or there's something going wrong while we transmit the packets.

**Comment by DSH105** [comment]
@CaptainBern Remember we also tested this on 1.7.9, which used to send the packets correctly, but it also doesn't work :\

**Comment by CaptainBern** [comment]
This has been fixed thanks to @SupaHam
