### ISSUE TITLE
JavaDoc link wrong in the wiki

### ISSUE THREAD

**Issue by william-reed** [DSH105/HoloAPI#110]
I would create a pull request for this but apparently that is not a feature yet for wiki's which is odd... But anyhow the link on this [page](https://github.com/DSH105/HoloAPI/wiki/API) where it says "refer to the java docs"  points to http://ci.hawkfalcon.com/job/HoloAPI/javadoc/ when it should point to http://ci.dsh105.com/job/HoloAPI/javadoc/

**Comment by drtshock** [comment]
Fixed, thanks :)
