### ISSUE TITLE
Text is falling through the floor and never comes back and will then be replaced

### ISSUE THREAD

**Issue by niju-me** [DSH105/HoloAPI#14]
I have sometimes the problem that on or two lines of a hologram are falling down straight through the floor and they never come up again. (not even after /holo reload or /reload) And additionally another hologram  created after it will be positioned in the other one with the missing lines:

That is the result http://puu.sh/7l05H.png
And that's the data.yml content: http://puu.sh/7l08l.txt
Maybe it mixes because both are having nearly the same X and Z coords...
I am using holoapi 1.0.3
(The text is german, but I believe that doesn't matter...)

**Comment by CaptainBern** [comment]
Try using 1.0.5 (https://github.com/DSH105/HoloAPI/releases/tag/v1.0.5) If you still have this issue then, please report back and I will take a look at it.

**Comment by niju-me** [comment]
Know a whole hologram disappears on move of another one and as the last time, two lines are now 'attached' to the other one. The issue persists.

Btw. on some places the text is not readable/very dark. Do you know the reason for it? Could it be because of the entities of the text are in the blocks beneath the text and minecraft handles it like they are behind a wall?

Example (The light lines are from the other hologram 20 blocks away):
http://puu.sh/7m9F0.png

**Comment by DSH105** [comment]
Try using /holo refresh <id>

**Comment by DSH105** [comment]
@Sehales Still having problems?
