### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by Mike0so** [DSH105/HoloAPI#15]
I searched every... Im coding some addons for this plugin. 
Where i could fine a Javadoc?

could you please sent me a link?

**Comment by DSH105** [comment]
I'm working on the JavaDocs :\

You can come and talk to me in IRC right now if you need help.

**Comment by DSH105** [comment]
https://github.com/DSH105/HoloAPI/commit/ac23e54a442143e1b111076f164d4fcdd703a630

Enjoy :)

**Comment by DSH105** [comment]
The JavaDocs can now be [found over on this page](http://ci.hawkfalcon.com/job/HoloAPI/javadoc/).
