### ISSUE TITLE
URL support for text based holograms ?

### ISSUE THREAD

**Issue by Miaourt** [DSH105/HoloAPI#16]
Like the title say, any plan for a future implementation of url cheking of a "txt" from the web ? :) it could be cool for a news based system or a dynamic tweet feed... etc xD

**Comment by CaptainBern** [comment]
This is certainly possible but will most likely never added. A website is more then a bunch of text, it contains several markup tags so your text will probably contain a lot of <div> tags etc. We could, on the other hand, use a paste service like pastebin.

**Comment by Miaourt** [comment]
Personally, i don't see any problem for "read" a TexT file from a server to the web :x you can't read any file like that : http://k0n3ko.net/newserveurs/news.txt ? >_<

**Comment by CaptainBern** [comment]
Oh well, I will take a look at it :)

**Comment by Miaourt** [comment]
Thank a lot !

**Comment by Miaourt** [comment]
Oh, sorry for close this x')

**Comment by DSH105** [comment]
Added :3

Use `/holo readtxt <url>` to read from a text file.

**Comment by Miaourt** [comment]
Yeah, thank ! :3
