### ISSUE TITLE
[Request] Support for showNPCs

### ISSUE THREAD

**Issue by BriannaThorez** [DSH105/HoloAPI#17]
My self and many server admins use sentrys and NPCS. via citizens2,denizen, and/or sentry. Would it be possible to show floating damage indicators on these as well? It works fine if just a citizens NPC but once I add trait sentry the indicators do not show :/

**Comment by DSH105** [comment]
I'll look into fixing that that for you ;).

**Comment by CaptainBern** [comment]
Added to the TODO's. I will close this for now.
