### ISSUE TITLE
Generated Holograms do not despawn correctly

### ISSUE THREAD

**Issue by BriannaThorez** [DSH105/HoloAPI#18]
Latest dev build
Spigot build 1.7.2 #1300

Issue:
one in five generated damage indicators do not unload. They remain static in location(relogging on to server clears artifacts untill new ones get stuck)
Detail:
My friend and I both see "flying wither skulls" they're definitely from the hologram plugin but we don't know what it means. I do /holo reload and it returns to normal(they disappear). While the skulls are out and about it causes a good amount of client-side lag. Not sure if any one else has encountered this?
The skulls are linked to the animals/mobs dieing in lava a very far distance directly below them and after they're dead (you can see the dmg indicators from the surface) the indicators do not despawn but the skulls do.

The second line in my two line server welcome text hologram loads one in thirty times. Usually after it loads it disappears also. The first line however displays fully about 95% of the time.

Both of these have been persistent since I started using holoapi a week or two ago

**Comment by CaptainBern** [comment]
We'll take a look at the issue...

**Comment by DSH105** [comment]
Fixed indicators not despawning:
https://github.com/DSH105/HoloAPI/commit/fe4b7727396d45d996375ba7c41981b162c9f25f

The flying wither skulls are unfortunately something that I can't fix at this stage :(

**Comment by DSH105** [comment]
Anything else that needs to be fixed up? :)

Also, is the issue with the lines not appearing still occurring?

**Comment by DSH105** [comment]
Issue with lines not appearing fixed. See #14. I believe that fixes everything in this ticket :)

**Comment by BriannaThorez** [comment]
Yes i think it is all fixed i have not any issues in quite a while!

**Comment by DSH105** [comment]
Awesome. We're making progress :DD
