### ISSUE TITLE
Damage indicators stuck

### ISSUE THREAD

**Issue by Adondriel** [DSH105/HoloAPI#19]
I am having issues with damage indicators.
Sometimes the damage indicator tags get stuck in the air, not being delete until i restart the server.
I am using dev build #90

**Comment by BriannaThorez** [comment]
same. But mine clear on /holoreload and relog onto server

**Comment by DSH105** [comment]
We are looking into the issue :)

**Comment by Adondriel** [comment]
I am using a multi world plug in if that is of any help.

**Comment by DSH105** [comment]
Closing as a duplicate of #18
