### ISSUE TITLE
?????? Pic

### ISSUE THREAD

**Issue by TJFJefroy** [DSH105/HoloAPI#2]
This happen after a few reloades.
http://minez-tjf.bugs3.com/Jef/2014-02-26_16.17.21.png

**Comment by drtshock** [comment]
Reloading the plugin or the server?

**Comment by TJFJefroy** [comment]
server but i think this will also heppen if i only reload the plugin because there is a bug in bukkit. Bukkit can't save Utf-8 in configs.

**Comment by TJFJefroy** [comment]
How i said even if i reload only the plugin this happen and i think the id is a little buggy because after 1 come 66?

**Comment by drtshock** [comment]
Try the holo reload command instead of reloading bukkit. And bukkit can handle the config files just fine.

**Comment by TJFJefroy** [comment]
But the server restart everyday and no you can test it.

**Comment by DSH105** [comment]
HoloAPI should be loading these images just fine. If it isn't, update to the latest dev build (14 at time of post), clear the `data.yml` and create your holograms again.

Also, the ID system has been redone so that it is more friendly :).
