### ISSUE TITLE
Color Coded not working

### ISSUE THREAD

**Issue by leimekiller** [DSH105/HoloAPI#20]
Color codes are not working in my holograms.

![qxfun1z](https://f.cloud.github.com/assets/5221322/2413176/29a82cdc-aadb-11e3-8035-30a94e915d93.jpg)

**Comment by DSH105** [comment]
What version of HoloAPI are you using?

**Comment by leimekiller** [comment]
The latest dev build.

**Comment by DSH105** [comment]
How are you creating it? Colour codes should work

**Comment by leimekiller** [comment]
First when you create them, they work, but after a reload the &'s change into questionmarks. So after that I change the questionmarks into &'s again and then it does this.

**Comment by DSH105** [comment]
Is it a normal hologram or animated?

**Comment by DSH105** [comment]
Try build 92
https://github.com/DSH105/HoloAPI/commit/6706fc49682e28b78f41fddb259b3f5d929899ce

**Comment by leimekiller** [comment]
It was animated. I'll try build 92 now.

**Comment by leimekiller** [comment]
It's been fixed, thank you very much!

**Comment by DSH105** [comment]
o/
