### ISSUE TITLE
Double indicator spawn(one erroneous) with Axe and Fist. Swords work perfectly.

### ISSUE THREAD

**Issue by BriannaThorez** [DSH105/HoloAPI#21]
Build 104
Spigot1300

Hitting any mob, passive or hostile, with ANY axe does damage to its hp but two indicators spawn per hit. one shows -0.0<3, other shows correct value.
Fists/unarmed spawn two indicators also, one reads -1.0 and one reads -2.0 but my fists do only 2Dmg to any hitpoints so i think the -1.0<3 is the erroneous one

Swords function correctly!
No console errors

Mcmmo present

**Comment by CaptainBern** [comment]
Spigot handles a few things differently then Bukkit. Try the latest build, if it still doesn't work properly then I suggest you to switch over to CraftBukkit.

Closed.

**Comment by BriannaThorez** [comment]
lmao switch over to craft bukkit :p

thanks ill check it out(the latest build) thanks
