### ISSUE TITLE
Rare chat bubble sticking(failure to despawn)

### ISSUE THREAD

**Issue by BriannaThorez** [DSH105/HoloAPI#22]
Build104
Spigot1300
On rare occasion (one in 100) chat bubbles will fail to despawn similar to the damage indicators of older builds. Its not even enough to bother me but I figured i'd ticket any way haha.

**Comment by CaptainBern** [comment]
Thank you for making a ticket :). We will take a look at it.

**Comment by DSH105** [comment]
Try using 110 and report back if it's still occurring.

**Comment by BriannaThorez** [comment]
Okay will advise. So far absolutely zero reassurances but ill be sure and let you know if i see it again

**Comment by CaptainBern** [comment]
Should be fixed.
