### ISSUE TITLE
Request / Fix

### ISSUE THREAD

**Issue by ThisIsMyst** [DSH105/HoloAPI#23]
Request: Can you add a config option for disabling the name above your message.

Fix: If "rise" is set to false in the config, and you type 2 messages in quick succession, without waiting for the first one to disappear, they simply overlap, rather than the first message and the nametag moving up one line to "make room" for the new message.
Screenshot: http://gyazo.com/668f9492b90c22b5d809a6d0fa148135

EDIT:
2 More Issues:
1. If you /holo create somewhere, and then move, and then write the text and type "Done", it sets the text where you are, rather than where you did /holo create
2. If you /holo edit, formatting codes (at least color ones, didn't try others) do not work, even if the the text before the edit did have color.

Thanks :)

**Comment by DSH105** [comment]
- Option to disable names in chat bubbles was added a few days ago https://github.com/DSH105/HoloAPI/commit/e9d3376e3aef0b938d384dc3f86fdc49a64b1cc5.
- I'm working on a system which will handle chat bubbles a little better and prevent overlapping
- `/holo create` - I (personally) prefer it that way. It's also easier to keep track of :\
- `/holo edit` - I've just fixed that :). https://github.com/DSH105/HoloAPI/commit/38d6f6f3db35614307416736020f0f8e85714ca8

**Comment by DSH105** [comment]
Fix chat bubbles overlapping:
https://github.com/DSH105/HoloAPI/commit/1edeca11ef8e29e841ebeb6d2aa93c00b75c12db

**Comment by CaptainBern** [comment]
Fixed.

**Comment by DSH105** [comment]
<3
