### ISSUE TITLE
Stop signs rotating and following player

### ISSUE THREAD

**Issue by RiCkYB-667** [DSH105/HoloAPI#26]
Hi there! Love your work!
Only if there was an option to stop holo-signs to rotate and follow players, would be awesome!
You could have a "setface" command to be able to give a certain degree 0-360 where it should face and not rotate around.
Would look like proper holographic displays, huh?
Please let me know if this is possible!
Thank you very much for all your hard work!
Cheers,
Ricky

**Comment by CaptainBern** [comment]
This is not possible and entirely done client-side.

**Comment by RiCkYB-667** [comment]
Understood. Thanks for the info. ;)
