### ISSUE TITLE
Failed to create an image "hologram"

### ISSUE THREAD

**Issue by niju-me** [DSH105/HoloAPI#3]
I first got those messages when doing /holo reload:
"Configuration files reloaded"
"Error for input string: /holo reload. Use /holo help for help"

When doing /holo create image secon  (secon is the image name in the config and it is exactly the same configuration as in your wiki, just another image)
I get "an internal error occured..." (the standard bukkit unhandled exception on command execution message) and the console log says:
"No such method getHandle"
"[Reflection] Failed retrieve the NMS Player-Object of:Sehales"
"null" 
Stacktrace: http://pastebin.com/wxpjwSBA

After that no image appears ingame and nothing else happens.

**Comment by niju-me** [comment]
The same errors occur when trying to create a normal text based hologram as well.

**Comment by TJFJefroy** [comment]
Its fixed but its not compiled so you can compile it for yourself like me or you have to wait.

**Comment by hawkfalcon** [comment]
It's complied on my CI.

**Comment by drtshock** [comment]
Was fixed here https://github.com/DSH105/HoloAPI/commit/bea0a6c2d94439f26290bbb1822853bcb7606953
