### ISSUE TITLE
ErrorStack then trying to remove hologram from console

### ISSUE THREAD

**Issue by pavog** [DSH105/HoloAPI#32]
Hi. I tried to use holo remove <id> from console and got this error: 
![holoerror](https://f.cloud.github.com/assets/4786628/2492191/99ee2206-b217-11e3-85ee-4f77ac47338a.jpg)

Please fix it so that I can use holo remove from console, too!

BTW: Great plugin & developerAPI, thanks for this!

**Comment by DSH105** [comment]
https://github.com/DSH105/HoloAPI/commit/d48af9b3579189d146fbb5c7276e059c2ba8ea02
