### ISSUE TITLE
Server kick/Crash when using images with the holoapi plugin

### ISSUE THREAD

**Issue by Freeek323** [DSH105/HoloAPI#34]
Hey pal, i went to your live chat page and was directed here. 

I'm having an issue with the holoAPI plugin.

the text area of the plugin works flawlessly, everything is fine.

Inititally when using the image section, i imported an image that had a height of 95, and was 600 wide.

i changed the config to 95 height thinking 'yeah that'll be fine'. 

Nope, took my fps from 100+ down below 5 and froze my game. But that's understandable for a high resolution.

So i found a smaller image, set height to 40. Width was around 300

same issue, but it didn't crash my game. I could move around okay at 5fps. when i move away from the holo and it 'de-spawns' from view, my fps goes up fine.

Thing is though, after leaving it there for a minute or so, it kicked all my players and crashed the server.

I then tried an even smaller image at 20x80.

Set height to 20.

My fps drops (again), this time not as bad, as i get 19fps.

few minutes after though, same thing. Kicked then crashed.

I did record the logs of the crash, and put it on pastebin here :: http://pastebin.com/CxbSfHVN

I'm sorry if this is documented incorrectly. I literally made a github account for this purpose of messaging you.

also i'm running the latest stable release of craftbukkit (if that helps at all).

Thanks. - Freeek

**Comment by DSH105** [comment]
Remember that an image 300 wide is huge for a hologram. Try reducing it a little and see if that does anything.

The stack trace was reported and fixed here: #32.

**Comment by DSH105** [comment]
That might fix it. Holograms can't be over 30 lines long due to these crashes

**Comment by DSH105** [comment]
@Freeek323 Any more information or updates on this?

**Comment by DSH105** [comment]
If this isn't resolved, re-open the ticket. For now, I'm going to say that it's fixed, because I haven't come across it since that commit :)
