### ISSUE TITLE
TagFormat Commit - noclassdeffounderror

### ISSUE THREAD

**Issue by williamburns** [DSH105/HoloAPI#46]
I have included holoapi in my build path and in the onenable have tried to add new tags i.e. HoloAPI.getTagFormatter().addFormatter....... etc.

This did not work for some reason. I get a noclassdeffounderror every time I try to use the TagFormat class.

Thanks!

**Comment by Favorlock** [comment]
Did you place this in the plugin folder? It's a plugin after all.

**Comment by DSH105** [comment]
@WilliamBurns Make sure you're using a version of HoloAPI that has this change.

**Comment by williamburns** [comment]
@Favorlock It is in the plugins folder.

@DSH105 I am using the latest version, but the weird thing is, in eclipse it seems to be working, no errors, but when I go to run, it just doesn't work...

**Comment by DSH105** [comment]
@WilliamBurns Then obviously the version in your server files isn't the same as your dependency.

**Comment by williamburns** [comment]
Yes sorry I didn't first understand what you meant, you were completely right and it is all fixed! Thanks!

**Comment by DSH105** [comment]
Awesome :D
