### ISSUE TITLE
Attempting to create holograms using a command block causes unhandled exception

### ISSUE THREAD

**Issue by XHawk87** [DSH105/HoloAPI#47]
I understand this is not currently possible, but even so the exception should be handled. 

It would be a very nice feature to be able to dynamically create/destroy and manage holograms using commands blocks though. This sort of thing would be very handy for command-based scripting plugins too.

Stack trace:
http://pastebin.com/fw80E1Jc

**Comment by DSH105** [comment]
I'm currently working on this :). Thanks for the suggestion! ;3

**Comment by DSH105** [comment]
Really sorry for the lack of speed on implementing this :(.

As of this commit (https://github.com/DSH105/HoloAPI/commit/14f2d3c7ac8f9c7a3d59f2196157679cefaa0de0), many new commands have been added to support command blocks. See `/holo help` for the new help information on these commands.

**Comment by XHawk87** [comment]
Good work. I'll be trying it out soon. Very much appreciated

**Comment by XHawk87** [comment]
I got a NPE on attempting to use /holo help:

http://pastebin.com/h72v0yCr

A different one when doing it from console:

http://pastebin.com/91930nn4

I was using the latest commit (https://github.com/DSH105/HoloAPI/commit/4ff893fde0a13a58c7a3071452bfb4f3d3bddb8d))

**Comment by DSH105** [comment]
I'll have to optimise the help pages to make them a lot neater.

**Comment by CaptainBern** [comment]
I will close this for now, if you have any questions, feel free to post it in here or on IRC.
