### ISSUE TITLE
Can you make have a option of disable feature in the indicator section?

### ISSUE THREAD

**Issue by demonslayer147** [DSH105/HoloAPI#49]
For example, for fire damage indicator, when mobs burning underground it created a load of this 
![capture](https://cloud.githubusercontent.com/assets/6226252/2623321/6448482c-bce7-11e3-9a67-d1fce509c09e.JPG)
It caused lag is there anyway to disable fire damage indicator?

**Comment by DSH105** [comment]
Sure. I'll add that for you :)

**Comment by DSH105** [comment]
Added ;D

Use `indicators.damage.enableType.fire` to disable it.
