### ISSUE TITLE
HoloAPI Images kicking all players from the server.

### ISSUE THREAD

**Issue by deerware** [DSH105/HoloAPI#51]
Bukkit version: 1.7.2-R0.4
Plugin version: 1.2.0
Kick message: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NegativeArraySizeException
The image will be created but everytime when some player(s) creating image(s), comming to image(s), or server loading image(s) it kick all players with this error.
![image](https://cloud.githubusercontent.com/assets/7270284/2686516/b93c82d6-c209-11e3-84df-ae9daddb7e68.png)

**Comment by deerware** [comment]
Oh. I forgot, In console it writes only normal disconnect:

> [08:18:23 INFO]: Coompiik[/88.101.123.232:15807] logged in with entity id 54694 at ([world] 6157.4844034772195, 80.3640006376021, 51681.36708018714)
> [08:18:23 INFO]: Loaded player file for Coompiik
> [08:18:23 INFO]: [Ultrabans] Logged Coompiik connecting from ip:88.101.123.232
> [08:18:30 INFO]: [AuthMe] Coompiik used the wrong password
> [08:18:33 INFO]: [AuthMe] Coompiik logged in!
>   ##  I comming from spawn to the image...
> [08:18:52 INFO]: Coompiik lost connection: Disconnected
> [08:18:52 INFO]: Removing player from memory: Coompiik
> [08:18:52 INFO]: Coompiik left the game.

**Comment by DSH105** [comment]
Thanks for you report. We'll look into this :)

**Comment by DSH105** [comment]
Try the latest dev build (252 and after). It should be fixed now) :).

**Comment by deerware** [comment]
Ok, I'll write you news if I be. on PC.

**Comment by deerware** [comment]
Where can I download this build? On bukkit is newest the relase 1.2.0 no builds.

**Comment by DSH105** [comment]
http://www.ci.hawkfalcon.com/job/HoloAPI/lastSuccessfulBuild/

**Comment by deerware** [comment]
THX, I try it now.

**Comment by deerware** [comment]
Bigger images kicking players... images with height 20, 30 is good, but 40 is kicking.

**Comment by CaptainBern** [comment]
For what reason? The same reason or something else?

**Comment by deerware** [comment]
I'll see, but I know the same.

2014-04-12 15:43 GMT+02:00 CaptainBern notifications@github.com:

> For what reason? The same reason or something else?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DSH105/HoloAPI/issues/51#issuecomment-40280656
> .

## 

S pozdravem,
Coompiik

**Comment by deerware** [comment]
Yes, the same
![image](https://cloud.githubusercontent.com/assets/7270284/2687284/1853710a-c249-11e3-9c5f-f2342abc4719.png)

**Comment by deerware** [comment]
WTF? Now I can't join in!
![image](https://cloud.githubusercontent.com/assets/7270284/2687286/4a49d6c2-c249-11e3-8764-d271c6adb739.png)

**Comment by CaptainBern** [comment]
Uhm well that's odd. Sure it's a HoloAPI issue?

**Comment by deerware** [comment]
Ok, Now I can join to the server :D the server lag do that I was in the game after I left

**Comment by deerware** [comment]
Sry for my bad english :D

**Comment by CaptainBern** [comment]
Your English is fine (: . No console errors or so?

**Comment by deerware** [comment]
No, console writes as I normal disconnect. THX :3, Kicking players doing HoloAPI Big images, beacause when is not generated big images its not falling, only when here is images height 40+

**Comment by deerware** [comment]
Sorry when I annoyng you, but I have an idea. It will by cool, when here will be command(try /holo laser) that will moving hologram laser :3
EDIT: Laser as Disco laser, no killing :D

**Comment by CaptainBern** [comment]
Hmm well I'll first look into the crash stuff.

**Comment by deerware** [comment]
ok

**Comment by DSH105** [comment]
Are you running that dev build? Holograms should automatically be cut down to 30 lines :\

**Comment by DSH105** [comment]
No response in over a week. I'm assuming that this is resolved.
