### ISSUE TITLE
TNT damage displays for non-living entities

### ISSUE THREAD

**Issue by Jikoo** [DSH105/HoloAPI#57]
I've only tested FallingBlock and ItemFrame entities with TNT damage. I'm not sure if any other damage types also display for them.
Edit: Having read the code, it appears any damage that can apply to nonliving entities will show - lava for minecarts, etc.

I run a plugin that allows FallingBlock "meteors" to drop and explode - with damage indicators on, this drops the server to about 15 TPS for 15-30 seconds with a very small radius ball.

Running HoloAPI 289 on Spigot 1434

**Comment by DSH105** [comment]
I'll fix this for you. Thanks for reporting the issue! :)

**Comment by DSH105** [comment]
Hopefully that commit should fix the problem.
