### ISSUE TITLE
Animated images (gif) or videos

### ISSUE THREAD

**Issue by rcl2748** [DSH105/HoloAPI#6]
Hello, can you please implement a feature that will allow to create animations like in the video that was shown in the plugin description?

--THanks, victor.

**Comment by DSH105** [comment]
Working on it ;). There are recent commits that show progress on this.

**Comment by rcl2748** [comment]
Thanks!, btw, is there a way I can help with the project? I have some Java experience

**Comment by DSH105** [comment]
If you feel like you can contribute something useful, feel free to make a Pull Request ;).

**Comment by rcl2748** [comment]
ok, thanks!

**Comment by DSH105** [comment]
Animated holograms are now fully implemented. Information on how to implement them will be on the Wiki soon.
