### ISSUE TITLE
What is the correct way to remove a hologram?

### ISSUE THREAD

**Issue by ryantheleach** [DSH105/HoloAPI#60]
@loopyluke and myself have been having a little trouble.

We are trying to make non persistent holograms, that is, won't survive server resets.

The idea being that someone right clicks with a map, deploys the hologram, then remove it under a variety of circumstances. (time, distance from player, never deploy 2 holograms)

I've asked luke to push the latest sources, which you will find at https://github.com/loopyluke/HolographicFactionMap/

**Comment by DSH105** [comment]
You can set the simplicity of a hologram using either the factory or hologram object (`.setSimplicity(true)`). Simple holograms won't be saved to file as normal holograms are.

`HoloAPI.getManager().stopTracking(hologram)` will completely remove the hologram from the manager and will automatically clear all active player views :).

**Comment by CaptainBern** [comment]
I will now close this issue. If you need any help with this or if something isn't clear feel free to comment here or join on irc.

**Comment by ryantheleach** [comment]
Yeah sorry I should have said something, this fixed the issue just fine.
