### ISSUE TITLE
Text is dark and hard to read

### ISSUE THREAD

**Issue by TalonPhoenix** [DSH105/HoloAPI#67]
When inside a building, text holograms will become dark and hard to read. For example, a white hologram will appear to be dark grey. This happens even if a hologram is created outside (where it is white), and then moved inside (once moved inside, the text appears grey).

Is there a way to ensure that the text does not become dark? It's unusable indoors because it is simply too difficult to read.

Using version 1.2.0

**Comment by DSH105** [comment]
Sorry, this is something we can't do anything about :(

**Comment by ryantheleach** [comment]
Use a brighter color?

**Comment by DSH105** [comment]
@ryantheleach It's a client-side limitation and has nothing to do with colours.
