### ISSUE TITLE
Simple holograms is not tracking

### ISSUE THREAD

**Issue by dpohvar** [DSH105/HoloAPI#69]
When i create simple hologram with HologramFactory, hologram is not displayed after rejoining

``` groovy
f = new com.dsh105.holoapi.api.HologramFactory(plugin)
f.withLocation(me.location)
f.withSimplicity(true)
f.withText('Text')
h = f.build()
```

If i use f.withSimplicity(true) hologram is updated, but I do not need to save it to a file

Is there any way to create a hologram that is not saved in the file and will be displayed to players after rejoining?

I use HoloAPI v1.2.3

**Comment by DSH105** [comment]
I have made changes a week or so ago (included in dev builds) that only restricts simple holograms from saving to file. That should fix your problem :).

**Comment by dpohvar** [comment]
HoloAPI v1.2.4-SNAPSHOT /03.05.2014/
Same problem with simple holograms
