### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by rcl2748** [DSH105/HoloAPI#7]
Hello, when will the API documentation come out? I really wanna make a plugin that will allow players to see their own face as a holography

**Comment by DSH105** [comment]
Hopefully I'll get some time to write it up tonight ;). If not, it will be done early this week.

**Comment by rcl2748** [comment]
k thx

**Comment by DSH105** [comment]
Documentation has been started [over on this page](https://github.com/DSH105/HoloAPI/wiki/API).

**Comment by rcl2748** [comment]
oh ok, thx, is it possible to create an image Holo from BufferedImage? I want to make a plugin that creates Holos from downloaded images online

**Comment by DSH105** [comment]
Use the ImageGenerator, which should be documented to a certain extent on that page.

**Comment by rcl2748** [comment]
oh ok, thx
