### ISSUE TITLE
Indicator --> Created a new hologram after reload

### ISSUE THREAD

**Issue by demonslayer147** [DSH105/HoloAPI#70]
When everytime i restarted a server or reload HoloAPI plugin, every indicator event that are occurred during the reloading process will stuck there and created a new hologram in the data.yml 
**\* USING THE LASTEST BUILD #338 ***

![bug](https://cloud.githubusercontent.com/assets/6226252/2870785/3552102a-d2e0-11e3-9d1b-14d992b53e51.JPG)

data.yml image
![capture2](https://cloud.githubusercontent.com/assets/6226252/2870786/4fff7070-d2e0-11e3-9ae3-538d6c35d366.JPG)

With a lot of the hologram created it caused client lag and have to remove manually through the data.yml

**Comment by Shadowgar** [comment]
Sorta same here. So using MCPC latest build on 1.6.4 ,chat bubbles are broken. They work, but on server reload, every chat created is stuck where the person typed it. and its filling up the flat file so fast its not worth keeping on. Also, non of the other features work like EXP, potions,damage,health.
The holograms work though.  Just nothing else.

**Comment by DSH105** [comment]
Sorry for not clarifying this earlier. I've tagged this issue in the commit above which fixes this problem. I hope you enjoy using HoloAPI :).
