### ISSUE TITLE
Showing after rejoin.

### ISSUE THREAD

**Issue by MYXOMOPX** [DSH105/HoloAPI#74]
When i create hologram with
`.withSimplicity(true)`
and rejoin - i don't more see this hologram.

What i should use for showing hologram after rejoining and don't save it to file

I use HoloAPI 1.2.4-Snapshot

**Comment by ryantheleach** [comment]
Just redisplay the hologram to the user when they rejoin?

**Comment by MYXOMOPX** [comment]
Holograms with 
`.withSimplicity(false)`
normally showing after rejoin. (But saves to file)
And redisplay - bad idea, because when i go far away from hologram and come back - i too not see it.

**Comment by CaptainBern** [comment]
I've added a new value to the HologramFactory and Hologram. You can now set the flag "setShowOnJoin" so (simple) Holograms will be shown on join. This was added here: https://github.com/DSH105/HoloAPI/commit/d6592c5edfdd9bfe12b63cbe4c442e47f467c52d

**Comment by DSH105** [comment]
Sorry for not clarifying this earlier. I've tagged this issue in the commit above which fixes this problem. I hope you enjoy using HoloAPI :).

I've also reverted the method addition by @CaptainBern as this is now not needed. `isSimple` will do the trick for you.
