### ISSUE TITLE
Chat/Damage Indicators being stored in data.yml and not being removed?

### ISSUE THREAD

**Issue by stuntguy3000** [DSH105/HoloAPI#75]
On behalf of @Recolance,

Why are Chat/Damage Indicators being stored in data.yml?

This is an issue because they don't get removed, causing startup lag when processing MASSIVE files.

**Comment by Chakyl** [comment]
This has also been happening to me with the latest version (v1.2.3).

**Comment by CaptainBern** [comment]
Should have been fixed in: https://github.com/DSH105/HoloAPI/pull/76

**Comment by DSH105** [comment]
Sorry for not clarifying this earlier. I've tagged this issue in the commit above which fixes this problem. I hope you enjoy using HoloAPI :).

The commit probably applies to this issue less than the others, but I figured it was important to let everyone know about this.
