### ISSUE TITLE
net.daboross.vault dependency causing build issues

### ISSUE THREAD

**Issue by desht** [DSH105/HoloAPI#78]
Hi, just trying to hook into HoloAPI from a plugin I'm working on, and I hit a problem where adding a dependency on HoloAPI caused the following build error:

```
[ERROR] Failed to execute goal on project sensibletoolbox: Could not resolve dependencies for project me.desht:sensibletoolbox:jar:1.0-SNAPSHOT: Failed to collect dependencies for [org.bukkit:bukkit:jar:RELEASE (provided), me.desht:dhutils-lib:jar:2.13.0-SNAPSHOT (compile), junit:junit:jar:3.8.1 (test), com.comphenix.protocol:ProtocolLib:jar:3.2.0 (provided), me.desht:landslide:jar:1.5.0 (provided), com.comphenix.attribute:AttributeStorage:jar:0.0.2-SNAPSHOT (compile), com.dsh105:HoloAPI:jar:1.2.0 (provided), org.mcstats.bukkit:metrics-lite:jar:R7 (compile)]: Failed to read artifact descriptor for net.milkbowl.vault:Vault:jar:1.2.23-SNAPSHOT: Could not transfer artifact net.milkbowl.vault:Vault:pom:1.2.23-SNAPSHOT from/to vault-repo (http://ci.herocraftonline.com/plugin/repository/everything): Connection to http://ci.herocraftonline.com refused: Connection refused -> [Help 1]
```

I managed track down the reference to ci.herocraftonline.com to the net.daboross.vault.vault-api artifact that you reference in the HoloAPI POM.  As an experiment, I cloned the latest HoloAPI, commented out the reference to vault-api and built it locally.  My plugin now builds fine when referencing my locally-built copy of HoloAPI.

It seems that the net.daboross.vault.vault-api dependency in your POM is a) unnecessary and b) is just causing build issues due to an outdated reference to ci.herocraftonline.com (which I believe is dead and gone).  Any reason not to just get rid of it?

**Comment by CaptainBern** [comment]
Ah! Thank you for reporting. I'll push a fix right away ;)

**Comment by desht** [comment]
Cheers :)

**Comment by CaptainBern** [comment]
Done :)
