### ISSUE TITLE
MCPC+1.6.4  Failed to find a matching method with name: h

### ISSUE THREAD

**Issue by Arrxzon** [DSH105/HoloAPI#83]
Hi i am getting a ton of spam in console and it is making it very difficult to monitor anything from console,
i would rather this get fixed than removing this awesome plugin.

using mcpc+1.6.4 with the latest dev build of HoloAPI

http://pastebin.com/Pt9kL43u
if you need the rest of the log due to multicrafts rate limit let me know
Thanks in advance

**Comment by DSH105** [comment]
Sorry for the delay in a fix!
