### ISSUE TITLE
Holograms not loading on restart

### ISSUE THREAD

**Issue by hockeymikey** [DSH105/HoloAPI#86]
I have 4 holograms on my server.  One in world and 3 in Hub.  2 of them are 3 line holograms (one in the hub other in world) they load just fine but the ones with 2 lines don't load unless you do "/holo reload" then they appear.

I get this error in the logs.
http://pastebin.com/9SmshDiU

**Comment by DSH105** [comment]
Thanks for reporting! ;D

**Comment by hockeymikey** [comment]
Works great now.  Thanks!
