### ISSUE TITLE
Damage Indicators are saved to config -> causes long startup time!

### ISSUE THREAD

**Issue by armbruer** [DSH105/HoloAPI#92]
I don't know why and when but the damage indicators are saved to config on my server and that causes my server to need a very very long startup time.

In my opinion they should not be saved at all to config. And they should be removed on reload.

**Comment by DSH105** [comment]
This has already been fixed. Try a development build :).

**Comment by armbruer** [comment]
Thanks. You guys are awesome. Love that plugin so much :)

**Comment by DSH105** [comment]
:D
