### ISSUE TITLE
Playercount placeholder overwrites user text

### ISSUE THREAD

**Issue by recon88** [DSH105/HoloAPI#94]
```
type: text
value: 'Players online: %serveronline:server%'
```

Results in just the "playercount" and overwrites my text. Is that intended?
Also would it be possible to add "playercount/maxplayers" instead of just "playercount" ?

**Comment by stuntguy3000** [comment]
If you mean max players, no.
Do you mean the entire line is set to "playercount" ?

**Comment by DSH105** [comment]
@recon88 We'll see what we can do :)

**Comment by cnr** [comment]
@recon88 The "maxplayers" thing sadly can't be done -- bungeecord doesn't offer an API for that

**Comment by recon88** [comment]
I saw several servers having playercount/maxplayers as holo. So I'm pretty sure it's possible somehow.
They were using a custom version of another holo plugin. Or they just modified the bungee api.

**Comment by recon88** [comment]
Nevermind, they probably just added the maxplayers count by hand which wasn't possible with HoloApi before you fixed the bug in this ticket.
I'll just use "%serveronline:server%/100" for now :)
