### ISSUE TITLE
Upcomming 1.8 features

### ISSUE THREAD

**Issue by macjuul** [DSH105/HoloAPI#96]
Whilst playing in the latest 1.8 snapshot I discovered that you can now rename ALL entities. The first thing I had to think of was HoloAPI.

So technicly its now possible to just spawn a wither skull with no direction and a custom (always visible) name.

This will also reduce lagg to some servers becous it uses no horses but only the witherskulls then.

**Comment by CaptainBern** [comment]
Yep, I've had a short conversation with Grum about this so we're well aware about this. We will be updating HoloAPI to use this new "feauture". 

I will now close this as it isn't a real "issue".

**Comment by DSH105** [comment]
This might also allow us to control view distance more closely :)

**Comment by Favorlock** [comment]
Woot! I'll probably hold off until 1.8 before I start utilizing HoloAPI :)
