### ISSUE TITLE
Darkened Text

### ISSUE THREAD

**Issue by Cmoor** [DSH105/HoloAPI#97]
I seem to have this issue where if im placing holograms inside builds, but not all the time, they darken. i usually move them around within the area so it lights up. i did notice though that placing a hologram on a beacon made it light back up, obviously because there is a hole to light. i might be looking in the wrong places but i cant find a fix for this. 
![2014-06-29_22 05 40](https://cloud.githubusercontent.com/assets/8010625/3425203/14d888d6-fffb-11e3-8c43-d93f6f9f00cd.png)

**Comment by DSH105** [comment]
This is currently not something we can fix :(. Try removing any blocks from ~50 above the hologram.

As of MC 1.8 (HoloAPI 2.x), this should no longer be a problem :).
